Repository klaus78/Data-Science-Flashcards, pull requests merged in 2023-10, with the labels that each got.

#12 Hacktoberfest/new questions ml dl
  _data/files/deep_learning.yml
  _data/files/machine_learning.yml
Labels: hacktoberfest

#16 Answered the help wanted questions.
  _data/files/data_analysis.yml
Labels: hacktoberfest, Hacktoberfest'23

#18 Adding Extra Question Regarding Machine Learning and Deep Learning
  Gemfile
  Gemfile.lock
  _data/files/dojos.yml
Labels: hacktoberfest, Hacktoberfest'23

#14 added questions in 3 files
  _data/files/data_analysis.yml
  _data/files/machine_learning.yml
  _data/files/statistics.yml
Labels: hacktoberfest, Hacktoberfest'23

#17 Added questions to deep learning and dojos
  _data/files/deep_learning.yml
  _data/files/dojos.yml
Labels: hacktoberfest, Hacktoberfest'23, hacktoberfest-accepted

#21 added more questions in Deep Learning
  _data/files/deep_learning.yml
Labels: hacktoberfest, hacktoberfest-accepted
